# Generated by Django 4.2.5 on 2023-11-04 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaColaboraciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('baja', models.BooleanField(default=False, verbose_name='Categoria Activa')),
            ],
            options={
                'verbose_name_plural': 'CategoriaColaboraciones',
            },
        ),
        migrations.CreateModel(
            name='CategoriaProyectos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('baja', models.BooleanField(default=False, verbose_name='Categoria Activa')),
            ],
            options={
                'verbose_name_plural': 'CategoriaProyectos',
            },
        ),
        migrations.CreateModel(
            name='Colaboracion',
            fields=[
                ('id_colaboracion', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='id_colaboracion')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('descripcion', models.TextField(null=True, verbose_name='descripcion')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('estado', models.BooleanField(default=False, verbose_name='estado')),
                ('foto', models.ImageField(null=True, upload_to='imagenes/', verbose_name='foto')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.categoriacolaboraciones')),
            ],
            options={
                'verbose_name_plural': 'Colaboraciones',
            },
        ),
        migrations.CreateModel(
            name='Personas',
            fields=[
                ('id_personas', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='id_persona')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('apellido', models.CharField(max_length=150, verbose_name='apellido')),
                ('fnac', models.DateField(verbose_name='fnac')),
                ('dni', models.CharField(max_length=50, verbose_name='dni')),
                ('email', models.EmailField(max_length=100, verbose_name='email')),
                ('estado', models.BooleanField(default=False, verbose_name='Diseñador')),
                ('foto_perfil', models.ImageField(blank=True, default='-', null=True, upload_to='imagenes/', verbose_name='foto_perfil')),
            ],
            options={
                'verbose_name_plural': 'Personas',
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id_proyecto', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='id_proyecto')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('descripcion', models.TextField(null=True, verbose_name='descripcion')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('foto', models.ImageField(null=True, upload_to='imagenes/', verbose_name='foto')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.categoriaproyectos')),
                ('personas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.personas')),
            ],
            options={
                'verbose_name_plural': 'Proyectos',
            },
        ),
        migrations.CreateModel(
            name='Participaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_participacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('colaboracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.colaboracion')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.personas')),
            ],
        ),
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id_comentarios', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='id_comentarios')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('comentario', models.TextField(verbose_name='comentario')),
                ('persona', models.ManyToManyField(to='administracion.personas')),
            ],
            options={
                'verbose_name_plural': 'Comentarios',
            },
        ),
        migrations.AddField(
            model_name='colaboracion',
            name='personas',
            field=models.ManyToManyField(through='administracion.Participaciones', to='administracion.personas'),
        ),
    ]
