# Generated by Django 4.2.5 on 2023-11-18 06:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaColaboraciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('estado', models.BooleanField(default=False, verbose_name='Categoria Activa')),
            ],
            options={
                'verbose_name_plural': 'CategoriaColaboraciones',
            },
        ),
        migrations.CreateModel(
            name='CategoriaProyectos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('estado', models.BooleanField(default=False, verbose_name='Categoria Activa')),
            ],
            options={
                'verbose_name_plural': 'CategoriaProyectos',
            },
        ),
        migrations.CreateModel(
            name='Colaboracion',
            fields=[
                ('id_colaboracion', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='id_colaboracion')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('descripcion', models.TextField(max_length=255, verbose_name='descripcion')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('estado', models.BooleanField(default=False, verbose_name='Estado Activo')),
                ('foto', models.ImageField(null=True, upload_to='imagenes/colaboraciones', verbose_name='foto')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.categoriacolaboraciones')),
            ],
            options={
                'verbose_name_plural': 'Colaboraciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Novedades',
            fields=[
                ('id_novedad', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='id_novedad')),
                ('titulo', models.CharField(max_length=200, verbose_name='Titulo')),
                ('mensaje', models.CharField(max_length=250, verbose_name='Mensaje Corto')),
                ('estado', models.BooleanField(default=False, verbose_name='Estado Activo')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('contenido', models.TextField(verbose_name='Contenido')),
                ('imagen', models.ImageField(blank=True, default='', null=True, upload_to='imagenes/novedades/', verbose_name='Imagen Novedad')),
            ],
            options={
                'verbose_name_plural': 'Novedades',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Personas',
            fields=[
                ('id_personas', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='id_persona')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('apellido', models.CharField(max_length=150, verbose_name='apellido')),
                ('fnac', models.DateField(verbose_name='fnac')),
                ('dni', models.CharField(max_length=50, verbose_name='dni')),
                ('email', models.EmailField(max_length=100, verbose_name='email')),
                ('estado', models.BooleanField(default=False, verbose_name='Diseñador')),
                ('foto_perfil', models.ImageField(blank=True, default='avatar.jpg', null=True, upload_to='imagenes/perfiles/', verbose_name='foto_perfil')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Personas',
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id_proyecto', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='id_proyecto')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('descripcion', models.TextField(max_length=255, verbose_name='descripcion')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('estado', models.BooleanField(default=False, verbose_name='Estado Activo')),
                ('foto', models.ImageField(null=True, upload_to='imagenes/proyectos/', verbose_name='foto')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.categoriaproyectos')),
                ('personas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.personas')),
            ],
            options={
                'verbose_name_plural': 'Proyectos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Participaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_participacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('colaboracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.colaboracion')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.personas')),
            ],
            options={
                'verbose_name_plural': 'Participaciones',
            },
        ),
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id_comentarios', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='id_comentarios')),
                ('tipo', models.CharField(choices=[('PRO', 'Proyecto'), ('COL', 'Colaboracion')], default='PRO', max_length=3)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('comentario', models.TextField(verbose_name='comentario')),
                ('estado', models.BooleanField(default=True, verbose_name='Visible')),
                ('id_persona', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.personas')),
                ('nro_proyecto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.proyecto')),
            ],
            options={
                'verbose_name_plural': 'Comentarios',
            },
        ),
        migrations.AddField(
            model_name='colaboracion',
            name='personas',
            field=models.ManyToManyField(through='administracion.Participaciones', to='administracion.personas'),
        ),
    ]
