# Generated by Django 4.2.5 on 2023-10-23 19:33

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personas',
            fields=[
                ('id_personas', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='id_persona')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('apellido', models.CharField(max_length=150, verbose_name='apellido')),
                ('fnac', models.DateField(verbose_name='fnac')),
                ('dni', models.CharField(max_length=50, verbose_name='dni')),
                ('email', models.EmailField(max_length=100, verbose_name='email')),
                ('estado', models.BooleanField(default=False, verbose_name='estado')),
                ('foto_perfil', models.ImageField(null=True, upload_to='imagenes/', verbose_name='foto_perfil')),
            ],
            managers=[
                ('activos', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id_proyecto', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='id_proyecto')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('descripcion', models.TextField(null=True, verbose_name='descripcion')),
                ('foto', models.ImageField(null=True, upload_to='imagenes/', verbose_name='foto')),
                ('categoria', models.CharField(choices=[('NIG', 'Ninguna'), ('VEN', 'Ventas'), ('EDU', 'Educacion'), ('ENT', 'Entretenimiento'), ('MUS', 'Musica'), ('DIS', 'Diseño')], default='NIG', max_length=3)),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='fecha')),
                ('personas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.personas')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id_comentarios', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='id_comentarios')),
                ('comentario', models.TextField(verbose_name='comentario')),
                ('persona', models.ManyToManyField(to='administracion.personas')),
            ],
        ),
        migrations.CreateModel(
            name='Colaboracion',
            fields=[
                ('id_colaboracion', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='id_colaboracion')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('descripcion', models.TextField(null=True, verbose_name='descripcion')),
                ('foto', models.ImageField(null=True, upload_to='imagenes/', verbose_name='foto')),
                ('estado', models.BooleanField(default=False, verbose_name='estado')),
                ('personas', models.ManyToManyField(to='administracion.personas')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
