# Generated by Django 4.2.5 on 2023-10-24 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personas',
            name='foto_perfil',
            field=models.ImageField(null=True, upload_to='imagenes/', verbose_name='Foto de Perfil'),
        ),
    ]
