# Generated by Django 4.2.5 on 2023-11-05 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_alter_participaciones_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Novedades',
            fields=[
                ('id_novedad', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='id_novedad')),
                ('titulo', models.CharField(max_length=200, verbose_name='Titulo')),
                ('mensaje', models.CharField(max_length=250, verbose_name='Mensaje Corto')),
                ('estado', models.BooleanField(default=False, verbose_name='Estado Activo')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('contenido', models.TextField(verbose_name='Contenido')),
                ('imagen', models.ImageField(blank=True, default='', null=True, upload_to='imagenes/novedades/', verbose_name='Imagen Novedad')),
            ],
            options={
                'verbose_name_plural': 'Novedades',
            },
        ),
        migrations.AlterField(
            model_name='colaboracion',
            name='descripcion',
            field=models.CharField(default=0.0009000900090009, max_length=255, verbose_name='descripcion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='colaboracion',
            name='estado',
            field=models.BooleanField(default=False, verbose_name='Estado Activo'),
        ),
        migrations.AlterField(
            model_name='colaboracion',
            name='foto',
            field=models.ImageField(null=True, upload_to='imagenes/colaboraciones', verbose_name='foto'),
        ),
        migrations.AlterField(
            model_name='personas',
            name='foto_perfil',
            field=models.ImageField(blank=True, default='', null=True, upload_to='imagenes/perfiles/', verbose_name='foto_perfil'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='descripcion',
            field=models.CharField(default=11, max_length=255, verbose_name='descripcion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='estado',
            field=models.BooleanField(default=False, verbose_name='Estado Activo'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='foto',
            field=models.ImageField(null=True, upload_to='imagenes/proyectos/', verbose_name='foto'),
        ),
    ]
