# Generated by Django 4.2.5 on 2023-11-05 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_novedades_alter_colaboracion_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentarios',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Visible'),
        ),
    ]
