# Generated by Django 4.2.5 on 2023-11-05 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0004_comentarios_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentarios',
            name='persona',
        ),
        migrations.AddField(
            model_name='comentarios',
            name='tipo',
            field=models.CharField(choices=[('PRO', 'Proyecto'), ('COL', 'Colaboracion')], default='PRO', max_length=3),
        ),
    ]
