# Generated by Django 4.2.5 on 2023-11-05 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0005_remove_comentarios_persona_comentarios_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentarios',
            name='nro_proyecto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.proyecto'),
        ),
    ]
